apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ayrk0jndd-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ayrk0jndd-go 
  name: ayrk0jndd-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ayrk0jndd-go 
